trigger:
- main

variables:
  git_user: "Team Flashbang"
  git_email: "dev@fb-hosting.net"
  git_url: "git@github.com:Team-Flashbang/SpawnTP.git"

pool:
  name: Default

steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
    git fetch --unshallow
    git switch $(basename $(Build.SourceBranch))
    git config --global user.email "$(git_email)"
    git config --global user.name "$(git_user)"
  displayName: Setup Git

- script: |
    git pull
    git remote set-url origin $(git_url)
    git push --force
  displayName: Mirror to GitHub